### ISSUE TITLE
Missing support for kaminari

### ISSUE THREAD

**Issue by RobWu** [Paxa/light_record#2]
Would be great if it could be used with kaminari

But get error from `pagination` helper:

```ruby
  undefined method `total_pages' for #<Array:0x007f8a0206bf88>
```

**Comment by andreslemik** [comment]
kaminari has [Paginating a generic Array object](https://github.com/amatsuda/kaminari#paginating-a-generic-array-object)

**Comment by RobWu** [comment]
Thanks.

**Comment by Paxa** [comment]
Not sure if using light_record for small data sets is a right choice...

Since kaminari will return scope extended by kaminari's params, but `#light_records` will return array.

You can use like this:
```
# controller
@payments = Payment.page(1).per(20)

#view
- @payments.light_records.each do |payment|
  = payment.time
```

---

BTW Using kaminari for big tables will cause performance issues. For example if you searching and paginating:

```
@paymnts = Payment.where(currency: "UDS").where("amount > 100").order("time desc")
```

SQL will be:
```sql
-- find records to display
SELECT  `payments`.* FROM `payments` where currency = "USD" AND amount > 100 LIMIT 20 OFFSET 0
-- count total records for "Last >" button
SELECT COUNT(*) FROM `payments` where currency = "USD" AND amount > 100
```


To show `Last »` button, or total found records it will need to scan all table for records matching our condition. That can be very expensive performance wise.
Instead we can patch kaminari to search only next 5 pages, so it will work same fast for tables with 1000 records and tables with 10_000_000 records.

https://gist.github.com/Paxa/8f5ad74febc32246f468499fc1aac4ad (also need to customize views to hide
